services:
  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:0aa26e284f05e6c77ae375b8c9c11d9eb6a448fb7bcd8d40f31cb6176189eb38
    container_name: edge-cloudflared
    restart: unless-stopped
    command: tunnel --metrics 0.0.0.0:8082 --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    volumes:
      - ${APPDATA_ROOT}/edge/cloudflared:/etc/cloudflared
    ports:
      - "8082:8082"
    networks:
      - public

  pihole:
    image: pihole/pihole:latest@sha256:f7d1be836e3bc608b56d82fc9904f5a831cdfbc0dc9c6d58f94e4c985c70038b
    container_name: edge-pihole
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - ${APPDATA_ROOT}/edge/pihole:/etc/pihole
      - ${APPDATA_ROOT}/edge/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    networks:
      - public

networks:
  public:
